services:
  - type: web
    name: lets-chat-api
    runtime: node
    region: frankfurt
    plan: free
    branch: main
    rootDir: .
    buildCommand: pnpm install && pnpm --filter @lets-chat/database generate && pnpm --filter api build
    startCommand: pnpm --filter api start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: API_URL
        value: https://lets-chat-api-wa43.onrender.com/api/v1
    healthCheckPath: /api/v1/health
    autoDeploy: true
